name: my-env 
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  # server dependencies:
  - pyjs
  - httpx >=0.28.1
  - httpx-ws >=0.8.2
  - jupyverse-api >=0.12.4
  - fps-frontend >=0.9.0
  - fps-lab >=0.9.0
  - fps-jupyterlab >=0.9.0
  - fps-noauth >=0.9.0
  - fps-contents >=0.10.0
  - fps-kernels >=0.10.2
  - fps-akernel-task >=0.1.3
  - fps-kernel-web-worker >=0.1.3
  - fps-file-id >=0.3.2
  - fps-file-watcher-poll >=0.1.1
  - fps-yjs >=0.10.5
  - akernel >=0.3.4
  - jupyter-collaboration-ui >=2.1.0
  - jupyter-docprovider >=2.1.0

  # kernel dependencies:
  - numpy
  - pandas
  - pydro
